# Generated by Django 2.1.7 on 2019-05-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190513_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='movie_click',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='portrait_click',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
