# Generated by Django 2.1.7 on 2019-05-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20190514_1548'),
        ('accounts', '0004_auto_20190515_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watch',
        ),
        migrations.AddField(
            model_name='user',
            name='checking',
            field=models.ManyToManyField(related_name='checked', to='movies.Movie'),
        ),
    ]
