# Generated by Django 2.1.7 on 2019-05-15 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190515_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperature',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='director',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='loving_actors',
        ),
        migrations.RemoveField(
            model_name='user',
            name='loving_directors',
        ),
        migrations.RemoveField(
            model_name='user',
            name='loving_staffs',
        ),
    ]
