# Generated by Django 2.1.7 on 2019-05-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20190515_1854'),
        ('accounts', '0007_auto_20190515_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_comment',
            field=models.ManyToManyField(related_name='liked', to='movies.Comment'),
        ),
    ]
