# Generated by Django 2.1.7 on 2019-05-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('en_name', models.CharField(blank=True, max_length=45)),
                ('filmography', models.TextField(blank=True)),
                ('portrait_url', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('en_name', models.CharField(blank=True, max_length=45)),
                ('filmography', models.TextField(blank=True)),
                ('portrait_url', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('en_name', models.CharField(blank=True, max_length=45)),
                ('filmography', models.TextField(blank=True)),
                ('roles', models.ManyToManyField(related_name='staffs', to='people.Role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='director',
            name='roles',
            field=models.ManyToManyField(related_name='directors', to='people.Role'),
        ),
        migrations.AddField(
            model_name='actor',
            name='roles',
            field=models.ManyToManyField(related_name='actors', to='people.Role'),
        ),
    ]
