# Generated by Django 2.1.7 on 2019-05-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='code',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='director',
            name='code',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='code',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='director',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
