# Generated by Django 2.1.7 on 2019-05-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20190513_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='portrait_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='portrait_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
