# Generated by Django 2.1.7 on 2019-05-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190515_1728'),
        ('movies', '0006_auto_20190515_1728'),
        ('people', '0003_auto_20190513_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(null=True, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('en_name', models.CharField(blank=True, max_length=45)),
                ('filmography', models.TextField(blank=True)),
                ('portrait_url', models.CharField(max_length=200, null=True)),
                ('roles', models.ManyToManyField(related_name='peoples', to='people.Role')),
            ],
        ),
        migrations.RemoveField(
            model_name='actor',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='director',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='roles',
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
