# Generated by Django 2.1.7 on 2019-05-13 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=5000)),
                ('score', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=140)),
                ('en_title', models.CharField(blank=True, max_length=140)),
                ('open_year', models.CharField(blank=True, max_length=8)),
                ('prdt_year', models.CharField(blank=True, max_length=8)),
                ('running_time', models.IntegerField(blank=True)),
                ('nation', models.CharField(blank=True, max_length=50)),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('state', models.CharField(blank=True, max_length=10)),
                ('audience', models.IntegerField(blank=True)),
                ('rank', models.IntegerField(blank=True)),
                ('sales', models.IntegerField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('poster_url', models.CharField(blank=True, max_length=200)),
                ('actors', models.ManyToManyField(related_name='movies', to='people.Actor')),
                ('directors', models.ManyToManyField(related_name='movies', to='people.Director')),
                ('genre', models.ManyToManyField(related_name='movies', to='movies.Genre')),
                ('staffs', models.ManyToManyField(related_name='movies', to='people.Staff')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='comment',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
