# Generated by Django 2.1.7 on 2019-05-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20190513_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='audience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='sales',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
