# Generated by Django 2.1.7 on 2019-05-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_trailer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='users',
            new_name='user',
        ),
    ]
