# Generated by Django 2.1.7 on 2019-05-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20190515_1728'),
        ('movies', '0006_auto_20190515_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='people',
            field=models.ManyToManyField(related_name='movies', to='people.People'),
        ),
    ]
