# Generated by Django 2.1.7 on 2019-05-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='large_poster_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
